version: '3.9'
services:
  db:
    container_name: ck-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./rdb/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    container_name: ck-redis
    image: redis/redis-stack
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes: 
      - cache:/data
  app:
    container_name: ck-app
    build: ./
    restart: on-failure
    depends_on:
      - db
      - cache
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      NODE_ENV: dev
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: postgres
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      CANVAS_SIZE: 30
    links:
      - db
      - cache
    volumes:
      - ./:/app
volumes:
  db:
    driver: local
  cache:
    driver: local