version: '3.9'
services:
  db:
    container_name: ck-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    container_name: ck-redis
    image: redis/redis-stack-server
    restart: always
    expose:
      - '6379:6379'
  bff:
    container_name: ck-bff
    image: ckoled/ck-eplace_bff
    restart: always
    depends_on:
      - db
      - cache
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: dev
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: postgres
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      CANVAS_SIZE: 20
    links:
      - db
      - cache
    volumes:
      - ./:/bff
  web:
    container_name: ck-web
    image: ckoled/ck-eplace_web
    restart: always
    depends_on:
      - bff
    ports:
      - '80:3000'
    links:
      - bff
    volumes:
      - ./:/web
volumes:
  db:
    driver: local
  cache:
    driver: local