version: '3.9'
volumes:
  db:
    driver: local
  cache:
    driver: local
services:
  db:
    container_name: ck-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    container_name: ck-redis
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - cache:/data
  bff:
    container_name: ck-bff
    image: ckoled/ck-eplace_bff
    restart: always
    depends_on:
      - db
      - cache
    expose:
      - '8080'
    environment:
      NODE_ENV: dev
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: postgres
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
      CANVAS_SIZE: 50
    links:
      - db
      - cache
  web:
    container_name: ck-web
    image: ckoled/ck-eplace_web
    restart: always
    depends_on:
      - bff
    expose:
      - '8080'
  nginx:
    container_name: ck-nginx
    image: nginx
    restart: always
    depends_on:
      - bff
      - web
    environment:
      API_HOST: bff
      API_PORT: 8080
      WEB_HOST: web
      WEB_PORT: 8080
    links:
     - bff
     - web
    ports:
      - '80:80'
    volumes:
      - ./config/eplace.template:/etc/nginx/conf.d/eplace.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/eplace.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 