kind: ReplicationController
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
  namespace: eplace
spec:
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ckoled/ck-eplace_web
        imagePullPolicy: IfNotPresent
        ports:
        - name: web-server
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    app: web
  namespace: eplace
spec:
  ports:
  - port: 8080
    targetPort: web-server
  selector:
    app: web
  type: NodePort
